name: quizmente
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#140B24"
  image: assets/merlac.png
  android: true
  ios: true
  android_12:
    image: assets/merlac.png
    color: "#140B24"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/questions/
    - assets/powerups.json
    - assets/image/Comodines.png
    - assets/image/Codice.png

  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
